bloodbank/urls.py
from django.contrib import admin
from django.urls import path,include
from bloodcamps import views
urlpatterns = [
    path('',views.index,name='index'),
    path('bloodcamps/',include('bloodcamps.urls')),
    path('admin/', admin.site.urls),
]

bloodcamps/urls.py
from django.urls import path
from bloodcamps import views
app_name='bloodcamps'
urlpatterns=[
    path('',views.camphome,name='camphome'),
    path('history/',views.history,name='history'),
    path('upcoming/',views.upcoming,name='upcoming'),
    path('newcamp/',views.newcamppage,name='newcamppage'),

]

bloodcamps/models.py
from django.db import models

# Create your models here.
Blood_Groups = (
    ('A+','A-'),
    ('A-', 'A+'),
    ('B+','B+'),
    ('B-','B-'),
    ('O+','O+'),
    ('O-','O-'),
    ('AB+', 'AB+'),
    ('AB-','AB-'),
)

Gender = (
    ('male','Male'),
    ('female', 'Female'),
    ('transgender', 'Transgender'),
)

class bloodcamp(models.Model):
    date=models.DateField()
    place=models.CharField(blank=False,null=False,max_length=150)
class bloodcampdonor(models.Model):
    firstname=models.CharField(blank=False,null=False,max_length=150)
    lastname=models.CharField(blank=False,null=False,max_length=150)
    email=models.EmailField(unique=True)
    phone = models.CharField(max_length = 11, blank = True)
    gender=models.CharField(max_length=15,choices=Gender)
    date=models.DateField(auto_now=True,auto_now_add=False)
    blood=models.CharField(max_length=10,choices=Blood_Groups)
    bloodcamp=models.ForeignKey(bloodcamp,on_delete=models.CASCADE)

bloodcamps/forms.py
from django import forms
from bloodcamps.models import bloodcamp
class newcamp(forms.ModelForm):
    class Meta:
        model=bloodcamp
        fields='__all__'

bloodcamps/views.py
from django.shortcuts import render
from django.http import HttpResponse
from bloodcamps.models import bloodcamp,bloodcampdonor
from bloodcamps.forms import newcamp
# Create your views here.
def index(request):
    return render(request,'bloodcamps/index.html')
def camphome(request):
    return render(request,'bloodcamps/camphome.html')
def history(request):
    camps=bloodcamp.objects.order_by('date')
    print('camps:',camps)
    content = {
        'camps' : camps
    }

    return render(request,'bloodcamps/history.html',context=content)
def upcoming(request):
    return render(request,'bloodcamps/upcoming.html')
def newcamppage(request):
    form=newcamp()
    if request.method=='POST':
        form=newcamp(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return camphome(request)
        else:
            print('form invalid')
    return render(request,'bloodcamps/newcamp.html',{'form':form})

templates/bloodcamps/camphome.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CAMPS</title>
  </head>
  <body>
    <h1>U have come to blood camps page</h1>
    <ol>
      <li><a href="{% url 'bloodcamps:history' %}" style="text-decoration:none">History</a></li>
      <li><a href="{% url 'bloodcamps:upcoming' %}" style="text-decoration:none">Up coming</a></li>
      <li><a href="{% url 'bloodcamps:newcamppage' %}" style="text-decoration:none">New Camp</a></li>
    </ol>
  </body>
</html>

templates/bloodcamps/history.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>History</title>
    <style>

    </style>
  </head>
  <body>
    <h1>U came to history page</h1>
    {% if camps %}
    <table>

      <tr>
        <th>Date</th>
        <th>Place</th>
      </tr>
      {% for camp in camps %}
      <tr>
        <td>{{ camp.date }}</td>
        <td>{{ camp.place }}</td><br>
      </tr>
    </table>
      {% endfor %}
    {% else %}
    <p>No DATA</p>
    {% endif %}
    <h2><a href="{% url 'bloodcamps:camphome' %}" style="text-decoration:none">Back</a></h2>
  </body>
</html>

templates/bloodcamps/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
  </head>
  <body>
    <h1>/bloodcamps to go to BLOOD CAMPS</h1>
  </body>
</html>

templates/bloodcamps/newcamp.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Signup</title>
  </head>
  <body>
    <div class="container">
      <h1>please signup</h1>
      <form method="POST">
        {{ form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>

templates/bloodcamps/upcoming.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Upcoming</title>
  </head>
  <body>
    <h1>U have come to upcoming page</h1>
    <h2><a href="{% url 'bloodcamps:camphome' %}" style="text-decoration:none">Back</a></h2>
  </body>
</html>